version: "3"

services:

  app:
    build: yanishub1/application_python_asr_app:latest
    command: python app.py
    ports:
      - "5000:5000"
    container_name: my_app
    depends_on:
      - db
      - redis


  redis:
    image: yanishub1/redis:latest
    ports: ["6379"]
    container_name: redis

  db:
    image: yanishub1/mysql:latest
    hostname: db
    container_name: mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - mysql:/var/lib/mysql
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"   
     
volumes:
  mysql: